### ISSUE TITLE
Use Xcode developer directory instead of hardcoded paths

### ISSUE THREAD

**Issue by saagarjha** [kishikawakatsumi/SourceKitForSafari#11]
I noticed that the extension seems to hardcode the path to Xcode: https://github.com/kishikawakatsumi/SourceKitForSafari/blob/a5c0f16afd8baa7fe5b272fa796e242a8bac0fa2/SafariExtension/Settings.swift#L4

Perhaps it would be nicer to use the developer directory (`xcode-select -p`, `readlink /var/db/xcode_select_link`) instead?

**Comment by saagarjha** [comment]
Actually, doesn't `xcrun sourcekit-lsp` "just work"? Maybe it would be better to leave all the options unset by default and let `xcrun` pick the default toolchain and target for us, which means that we wouldn't need to hardcode a default value at all…

**Comment by kishikawakatsumi** [comment]
Hard coding is not a problem. Actually, the appropriate path is retrieved by `xcrun ... ` when it launched.
The reason I hardcoded the default values is so that it can display the standard values as placeholders for users who use less than Xcode 11.4.

But the "-beta" string is still there, which I overlooked 😓 Thanks for letting me know.
