### ISSUE TITLE
Can't get Chrome extension to work?

### ISSUE THREAD

**Issue by cameroncooke** [kishikawakatsumi/SourceKitForSafari#8]
I've followed the instructions to the letter, but haven't been able to get it to work with Chrome, works fine for public repos on Safari. So the LSP server is running, and I have the helper application running, with the window visible and with the window closed. Would be great if the helper application was a menu bar app that could run in background and lunch on startup too.

**Comment by kishikawakatsumi** [comment]
Could you please launch the helper application from Xcode to identify the problem? If communicating to LSP works correctly, a lot of logs are shown in the Xcode console. If there is any problems in that phase, please let me know what the logs showed. 

If it works, the cause is probably in the extension. To identify that, open Chrome's JavaScript console, and see whether JS errors happen.

**Comment by cameroncooke** [comment]
OK will do thanks, will let you know.
